### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by vishnupandey9426** [hemantapkh/PyBirthdayWish#2]
In pybirthdaywish.py there is error showing in 30 and 31th line

**Comment by pankajmeena07** [comment]
> In pybirthdaywish.py there is error showing in 30 and 31th line
> 

How to edit repository

**Comment by pankajmeena07** [comment]
> In pybirthdaywish.py there is error showing in 30 and 31th line
> 

Why

**Comment by hemantapkh** [comment]
Can you show what error did you get? @vishnupandey9426
